import { Router } from 'express';
import { config } from '../config.js';
import { getGridRuntimeConfig } from '../grid/client.js';
import { USDC_MINT } from '../solana.js';

export const capabilitiesRouter = Router();

capabilitiesRouter.get('/capabilities', (_req, res) => {
  res.json({
    product: 'decimal',
    version: 1,
    generatedAt: new Date().toISOString(),
    solana: {
      network: config.solanaNetwork,
      usdcMint: USDC_MINT.toBase58(),
      rpcUrl: config.solanaRpcUrl,
    },
    auth: {
      user: 'Authorization: Bearer <sessionToken>',
    },
    providers: {
      squads: {
        mode: 'direct',
        programId: config.squadsProgramId,
      },
      grid: getGridRuntimeConfig(),
    },
    apiSurface: {
      style: 'resource-oriented-json',
      openApi: 'GET /openapi.json returns the machine-readable OpenAPI 3.1 contract.',
      idempotency: 'Send Idempotency-Key on mutating requests that may be retried.',
      requestTracing: 'Every response includes x-request-id. Clients may provide x-request-id for trace correlation.',
      errors: {
        shape: {
          error: 'string',
          message: 'string',
          code: 'string',
          requestId: 'string',
        },
      },
    },
    workflows: [
      {
        id: 'single_payment',
        summary: 'Create one payment request, promote or create a payment order, create a Squads proposal, execute it, verify settlement by RPC, then export proof.',
        steps: [
          'POST /organizations/:organizationId/payment-requests',
          'POST /organizations/:organizationId/payment-requests/:paymentRequestId/promote',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/vault-proposals/payment-intent',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/confirm-submission',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/confirm-execution',
          'GET /organizations/:organizationId/payment-orders/:paymentOrderId/proof',
        ],
      },
      {
        id: 'csv_to_payment_run',
        summary: 'Preview CSV rows, import a payment run, create one Squads proposal for the batch, execute it, verify settlement by RPC, then export proof.',
        steps: [
          'POST /organizations/:organizationId/payment-runs/import-csv/preview',
          'POST /organizations/:organizationId/payment-runs/import-csv',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/vault-proposals/payment-run-intent',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/confirm-submission',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/confirm-execution',
          'GET /organizations/:organizationId/payment-runs/:paymentRunId/proof',
        ],
      },
      {
        id: 'document_to_payment_run',
        summary: 'Import a PDF/image invoice into extracted payment rows, review the resulting payment run, create one Squads proposal, execute it, verify settlement by RPC, then export proof.',
        steps: [
          'POST /organizations/:organizationId/payment-runs/from-document',
          'GET /organizations/:organizationId/payment-runs/:paymentRunId',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/vault-proposals/payment-run-intent',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/confirm-submission',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/confirm-execution',
          'GET /organizations/:organizationId/payment-runs/:paymentRunId/proof',
        ],
      },
      {
        id: 'collections',
        summary: 'Create expected inbound collections or import a receivables CSV. Collections are currently intent records; automatic inbound chain watching is intentionally detached from the lean MVP.',
        steps: [
          'POST /organizations/:organizationId/collections',
          'POST /organizations/:organizationId/collection-runs/import-csv/preview',
          'POST /organizations/:organizationId/collection-runs/import-csv',
          'GET /organizations/:organizationId/collections/:collectionRequestId',
          'GET /organizations/:organizationId/collection-runs/:collectionRunId',
          'GET /organizations/:organizationId/collections/:collectionRequestId/proof',
          'GET /organizations/:organizationId/collection-runs/:collectionRunId/proof',
        ],
      },
    ],
    endpointGroups: [
      {
        group: 'setup',
        routes: [
          'POST /auth/register',
          'POST /auth/login',
          'GET /auth/session',
          'POST /auth/verify-email',
          'GET /openapi.json',
          'GET /invites/:inviteToken',
          'GET /organizations',
          'POST /organizations',
          'GET /organizations/:organizationId/members',
          'GET /organizations/:organizationId/invites',
          'POST /organizations/:organizationId/invites',
          'POST /organizations/:organizationId/invites/:organizationInviteId/revoke',
          'POST /invites/:inviteToken/accept',
          'GET /personal-wallets',
          'POST /personal-wallets/challenge',
          'POST /personal-wallets/external',
          'POST /personal-wallets/embedded',
          'POST /personal-wallets/managed',
          'DELETE /personal-wallets/:userWalletId',
          'POST /personal-wallets/:userWalletId/sign-versioned-transaction',
          'GET /organizations/:organizationId/treasury-wallets',
          'POST /organizations/:organizationId/treasury-wallets/grid/create-account',
          'GET /organizations/:organizationId/treasury-wallets/:treasuryWalletId/grid/status',
          'GET /organizations/:organizationId/treasury-wallets/:treasuryWalletId/grid/balances',
          'POST /organizations/:organizationId/treasury-wallets/squads/create-intent',
          'POST /organizations/:organizationId/treasury-wallets/squads/confirm',
          'GET /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/detail',
          'GET /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/status',
          'GET /organizations/:organizationId/squads/proposals',
          'GET /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/config-proposals',
          'GET /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/config-proposals/:transactionIndex',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/config-proposals/add-member-intent',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/config-proposals/change-threshold-intent',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/vault-proposals/payment-intent',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/config-proposals/:transactionIndex/approve-intent',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/config-proposals/:transactionIndex/execute-intent',
          'POST /organizations/:organizationId/treasury-wallets/:treasuryWalletId/squads/sync-members',
          'GET /organizations/:organizationId/proposals',
          'GET /organizations/:organizationId/proposals/:decimalProposalId',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/confirm-submission',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/confirm-execution',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/approve-intent',
          'POST /organizations/:organizationId/proposals/:decimalProposalId/execute-intent',
          'GET /organizations/:organizationId/wallet-authorizations',
          'POST /organizations/:organizationId/wallet-authorizations',
          'GET /organizations/:organizationId/counterparty-wallets',
        ],
      },
      {
        group: 'input',
        routes: [
          'GET /organizations/:organizationId/payment-requests',
          'POST /organizations/:organizationId/payment-requests',
          'POST /organizations/:organizationId/payment-requests/import-csv/preview',
          'POST /organizations/:organizationId/payment-requests/import-csv',
          'POST /organizations/:organizationId/payment-runs/import-csv/preview',
          'POST /organizations/:organizationId/payment-runs/import-csv',
          'POST /organizations/:organizationId/payment-runs/from-document',
          'POST /organizations/:organizationId/collections',
          'POST /organizations/:organizationId/collections/import-csv/preview',
          'POST /organizations/:organizationId/collection-runs/import-csv/preview',
          'POST /organizations/:organizationId/collection-runs/import-csv',
          'POST /organizations/:organizationId/counterparty-wallets',
        ],
      },
      {
        group: 'control_and_execution',
        routes: [
          'GET /organizations/:organizationId/payment-orders',
          'POST /organizations/:organizationId/payment-orders',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/submit',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/prepare-execution',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/attach-signature',
          'GET /organizations/:organizationId/payment-runs',
          'POST /organizations/:organizationId/payment-runs/:paymentRunId/cancel',
          'POST /organizations/:organizationId/payment-runs/:paymentRunId/close',
          'POST /organizations/:organizationId/payment-runs/:paymentRunId/prepare-execution',
          'POST /organizations/:organizationId/payment-runs/:paymentRunId/attach-signature',
          'POST /organizations/:organizationId/collections/:collectionRequestId/cancel',
          'PATCH /organizations/:organizationId/counterparty-wallets/:counterpartyWalletId',
        ],
      },
      {
        group: 'verification_and_proof',
        routes: [
          'GET /organizations/:organizationId/payment-orders/:paymentOrderId/proof',
          'GET /organizations/:organizationId/payment-runs/:paymentRunId/proof',
          'GET /organizations/:organizationId/collections',
          'GET /organizations/:organizationId/collections/:collectionRequestId',
          'GET /organizations/:organizationId/collections/:collectionRequestId/proof',
          'GET /organizations/:organizationId/collection-runs',
          'GET /organizations/:organizationId/collection-runs/:collectionRunId',
          'GET /organizations/:organizationId/collection-runs/:collectionRunId/proof',
          'GET /organizations/:organizationId/audit-log',
          'GET /organizations/:organizationId/ops-health',
        ],
      },
    ],
    safetyNotes: [
      'The API never accepts or stores private keys.',
      'Prepared Squads transactions are signed by user-controlled personal wallets through the wallet/Privy flow.',
      'Submitted signatures are verified by Solana RPC before being stored as proposal evidence.',
      'Payment settlement is verified from RPC transaction token-account deltas.',
    ],
  });
});
