import { Router } from 'express';

export const capabilitiesRouter = Router();

capabilitiesRouter.get('/capabilities', (_req, res) => {
  res.json({
    product: 'decimal',
    version: 1,
    generatedAt: new Date().toISOString(),
    auth: {
      user: 'Authorization: Bearer <sessionToken>',
      internalWorker: 'x-service-token: <CONTROL_PLANE_SERVICE_TOKEN>',
    },
    apiSurface: {
      style: 'resource-oriented-json',
      openApi: 'GET /openapi.json returns the machine-readable OpenAPI 3.1 contract.',
      idempotency: 'Send Idempotency-Key on mutating requests that may be retried.',
      requestTracing: 'Every response includes x-request-id. Clients may provide x-request-id for trace correlation.',
      errors: {
        shape: {
          error: 'string',
          message: 'string',
          code: 'string',
          requestId: 'string',
        },
      },
    },
    workflows: [
      {
        id: 'single_payment',
        summary: 'Create one payment request, promote or create a payment order, submit it, prepare execution, attach signature, reconcile, then export proof.',
        steps: [
          'POST /organizations/:organizationId/payment-requests',
          'POST /organizations/:organizationId/payment-requests/:paymentRequestId/promote',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/submit',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/prepare-execution',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/attach-signature',
          'GET /organizations/:organizationId/payment-orders/:paymentOrderId/proof?format=markdown',
        ],
      },
      {
        id: 'csv_to_payment_run',
        summary: 'Preview CSV rows, import a payment run, prepare one batch USDC transaction, attach signature, reconcile, then export proof.',
        steps: [
          'POST /organizations/:organizationId/payment-runs/import-csv/preview',
          'POST /organizations/:organizationId/payment-runs/import-csv',
          'POST /organizations/:organizationId/payment-runs/:paymentRunId/prepare-execution',
          'POST /organizations/:organizationId/payment-runs/:paymentRunId/attach-signature',
          'POST /organizations/:organizationId/payment-runs/:paymentRunId/close',
          'GET /organizations/:organizationId/payment-runs/:paymentRunId/proof?format=markdown',
        ],
      },
      {
        id: 'collections',
        summary: 'Create expected inbound collections or import a receivables CSV, then let the existing onchain reconciliation layer prove what was collected.',
        steps: [
          'POST /organizations/:organizationId/collections',
          'POST /organizations/:organizationId/collection-runs/import-csv/preview',
          'POST /organizations/:organizationId/collection-runs/import-csv',
          'GET /organizations/:organizationId/collections/:collectionRequestId',
          'GET /organizations/:organizationId/collection-runs/:collectionRunId',
          'GET /organizations/:organizationId/collections/:collectionRequestId/proof',
          'GET /organizations/:organizationId/collection-runs/:collectionRunId/proof',
        ],
      },
      {
        id: 'exception_ops',
        summary: 'List reconciliation exceptions, inspect context, update metadata, add notes, and resolve or reopen.',
        steps: [
          'GET /organizations/:organizationId/exceptions',
          'GET /organizations/:organizationId/exceptions/:exceptionId',
          'PATCH /organizations/:organizationId/exceptions/:exceptionId',
          'POST /organizations/:organizationId/exceptions/:exceptionId/notes',
          'POST /organizations/:organizationId/exceptions/:exceptionId/actions',
        ],
      },
    ],
    endpointGroups: [
      {
        group: 'setup',
        routes: [
          'POST /auth/register',
          'POST /auth/login',
          'GET /auth/session',
          'POST /auth/verify-email',
          'GET /openapi.json',
          'GET /organizations',
          'POST /organizations',
          'GET /personal-wallets',
          'POST /personal-wallets/challenge',
          'POST /personal-wallets/external',
          'POST /personal-wallets/embedded',
          'POST /personal-wallets/managed',
          'GET /organizations/:organizationId/treasury-wallets',
          'GET /organizations/:organizationId/wallet-authorizations',
          'POST /organizations/:organizationId/wallet-authorizations',
          'GET /organizations/:organizationId/destinations',
          'GET /organizations/:organizationId/collection-sources',
        ],
      },
      {
        group: 'input',
        routes: [
          'GET /organizations/:organizationId/payment-requests',
          'POST /organizations/:organizationId/payment-requests',
          'POST /organizations/:organizationId/payment-requests/import-csv/preview',
          'POST /organizations/:organizationId/payment-requests/import-csv',
          'POST /organizations/:organizationId/payment-runs/import-csv/preview',
          'POST /organizations/:organizationId/payment-runs/import-csv',
          'POST /organizations/:organizationId/collections',
          'POST /organizations/:organizationId/collections/import-csv/preview',
          'POST /organizations/:organizationId/collection-runs/import-csv/preview',
          'POST /organizations/:organizationId/collection-runs/import-csv',
          'POST /organizations/:organizationId/collection-sources',
        ],
      },
      {
        group: 'control_and_execution',
        routes: [
          'GET /organizations/:organizationId/payment-orders',
          'POST /organizations/:organizationId/payment-orders',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/submit',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/prepare-execution',
          'POST /organizations/:organizationId/payment-orders/:paymentOrderId/attach-signature',
          'GET /organizations/:organizationId/payment-runs',
          'POST /organizations/:organizationId/payment-runs/:paymentRunId/cancel',
          'POST /organizations/:organizationId/payment-runs/:paymentRunId/close',
          'POST /organizations/:organizationId/payment-runs/:paymentRunId/prepare-execution',
          'POST /organizations/:organizationId/payment-runs/:paymentRunId/attach-signature',
          'POST /organizations/:organizationId/collections/:collectionRequestId/cancel',
          'PATCH /organizations/:organizationId/collection-sources/:collectionSourceId',
        ],
      },
      {
        group: 'verification_and_proof',
        routes: [
          'GET /organizations/:organizationId/reconciliation',
          'GET /organizations/:organizationId/reconciliation-queue/:transferRequestId',
          'GET /organizations/:organizationId/reconciliation-queue/:transferRequestId/explain',
          'POST /organizations/:organizationId/reconciliation-queue/:transferRequestId/refresh',
          'GET /organizations/:organizationId/transfers',
          'GET /organizations/:organizationId/payment-orders/:paymentOrderId/proof',
          'GET /organizations/:organizationId/payment-runs/:paymentRunId/proof',
          'GET /organizations/:organizationId/collections',
          'GET /organizations/:organizationId/collections/:collectionRequestId',
          'GET /organizations/:organizationId/collections/:collectionRequestId/proof',
          'GET /organizations/:organizationId/collection-runs',
          'GET /organizations/:organizationId/collection-runs/:collectionRunId',
          'GET /organizations/:organizationId/collection-runs/:collectionRunId/proof',
          'GET /organizations/:organizationId/audit-log',
          'GET /organizations/:organizationId/ops-health',
        ],
      },
      {
        group: 'worker_internal',
        routes: [
          'GET /internal/organizations',
          'GET /internal/organizations/:organizationId/matching-context',
          'GET /internal/matching-index',
          'GET /internal/matching-index/events',
        ],
      },
    ],
    safetyNotes: [
      'The API never accepts or stores private keys.',
      'Prepared execution packets require an external signer or wallet adapter to add a recent blockhash, sign, and submit.',
      'Submitted signatures are validated for Solana base58 signature shape before being stored as execution evidence.',
      'Internal worker routes require CONTROL_PLANE_SERVICE_TOKEN in production.',
    ],
  });
});
